### PR TITLE
Implement Early-Learning Regularisation

### PR DESCRIPTION
**Pull request by Alfred-N**
Implemented ELR loss. Note that I made modifications to noise.py that might be outdated now since Yineng improved it. 
~~Also it's not up to date with the changes Roderick/Yineng made to the wandb code.~~

### CODE REVIEW

**Comment by rlindsberg** [comment]
I will do a quick rebase, then we fix the conflicts.

**Comment by rlindsberg** [comment]
Before:
Skærmbillede 2021-05-13 kl  17 01 35

After:
Skærmbillede 2021-05-13 kl  17 07 14

Now starting rebase

**Comment by rlindsberg** [comment]
Rebase done

Skærmbillede 2021-05-13 kl  17 48 52

**Review by rlindsberg — APPROVED** [review]
The noise is different but I believe it's correct.

**Comment by rlindsberg** [comment]
After merge:
Do rebase!


#save old change
git add .
git stash

#pull new changes from master
git checkout master
git fetch
git pull master

#rebase master
git checkout my-old-branch
git rebase master
git checkout -b my-old-branch-rebased
git push origin my-old-branch-rebased

#re-apply old changes
git stash pop

**Review by YinengWang — APPROVED** [review]
1. There's still a problem with noise.py, when shuffling in dataloader is enabled. But it doesn't really matter, since we have a new dataloader which integrates a noise generator. So I approve the implementation.
2. To my understanding, the variable `stored_targets` in ELR_loss is updated every batch, so the computation graph has a very long dependency at the late stage of training. We can do experiments to check how long it takes to train for one epoch. If necessary, we need some optimizations.

**Comment by rlindsberg** [comment]
> * There's still a problem with noise.py, when shuffling in dataloader is enabled. But it doesn't really matter, since we have a new dataloader which integrates a noise generator. So I approve the implementation.
> * To my understanding, the variable `stored_targets` in ELR_loss is updated every batch, so the computation graph has a very long dependency at the late stage of training. We can do experiments to check how long it takes to train for one epoch. If necessary, we need some optimizations.

I think it's better that we chose one implementation of the noise thing and make sure it works. Instead of having two.

**Review by rlindsberg — CHANGES_REQUESTED** [review]
Yineng and I will investigate further...

**Review by rlindsberg — APPROVED** [review]
Due to the fact that the ELR is currently dependent on the noise implementation and we did double implementation of noise thingy, it is better to make an exception this time.
I will therefore merge in this PR and Yineng and I will evaluate further.
It's sad that we can't take both and have to drop one. So, next time please check with the team to avoid double work.

**Comment by rlindsberg** [comment]
Testing CIFAR10 with RESNET34, noise 0.2 with ELR

View run at https://wandb.ai/rlind/ResNet-ELR/runs/52339e7d

**Comment by rlindsberg** [comment]
Skærmbillede 2021-05-14 kl  12 41 25


Skærmbillede 2021-05-14 kl  12 41 26

Skærmbillede 2021-05-14 kl  12 41 27

**Review by rlindsberg — APPROVED** [review]
Test passed.

**Pull request merged**
